
version: '3.8'

services:
  frontend:
    
    build: ./client 
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
    
      REACT_APP_BACKEND_URL: http://backend:5000 

  backend:
   
    build: ./server 
    ports:
      - "5000:5000"
    environment:
     
      MONGO_URI: "mongodb+srv://sahil:%23Sahil91086@smallcasefunding.u6hi9kj.mongodb.net/smallcasefunding?retryWrites=true&w=majority&appName=smallcasefunding"
   